name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java 8 JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Run checks with Gradle
      run: ./gradlew check --continue
